version: 1.0.{build}
build_script:
- go build -o ldb-win ldb.go
artifacts:
- path: ldb-win
deploy:
- provider: GitHub
  auth_token:
    secure: /PM9ewDT9EE+jyfaMkBb7HXxt5FdvCBW7V8wG28H35a+3PA9pUXhF+s5HA+b+ZST
  artifact: ldb-win
  on:
    branch: master
    appveyor_repo_tag: true
